
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.StringTokenizer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajib Dey
 */
public class Report extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    private ArrayList<Passenger> PGA = new ArrayList<>();
    private ArrayList<flight> FT = new ArrayList<>(); private BufferedReader BR;
    public Report() {
        initComponents();
        this.readFlight();
        this.readPassenger();
        Display_panel.setVisible(false);
        Display_panel1.setVisible(false);
        
        for (int i=0; i< FT.size(); i++){
            Combo1.addItem(Integer.toString(FT.get(i).getIDs()));
            Combo2.addItem(Integer.toString(FT.get(i).getIDs()));
        }
    }
    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    private void readPassenger() {
        try {
            String line;
            BR = new BufferedReader(new FileReader("Passenger.csv"));

            while ((line = BR.readLine()) != null) {

                StringTokenizer stringTokenizer = new StringTokenizer(line, ",");

                while (stringTokenizer.hasMoreElements()) {
                    String PN = stringTokenizer.nextElement().toString();
                    String First = stringTokenizer.nextElement().toString();
                    String Last = stringTokenizer.nextElement().toString();
                    String Email1 = stringTokenizer.nextElement().toString();
                    int Flight_Number = Integer.parseInt(stringTokenizer.nextElement().toString());
                    int Rows = Integer.parseInt(stringTokenizer.nextElement().toString());
                    String SS = stringTokenizer.nextElement().toString();
                    char cc = SS.charAt(0);

                    Passenger pp = new Passenger(PN, First, Last, Email1, Flight_Number, Rows, cc);
                    PGA.add(pp);

                }

            }
            

        } catch (IOException | NumberFormatException e) {
            String errmsg = e.getMessage();
            System.out.println("File not found:" + errmsg);
        } // end of Catch
    }

    private void readFlight() {
        try {
            String line;
            BR = new BufferedReader(new FileReader("Flight.csv"));

            while ((line = BR.readLine()) != null) {

                StringTokenizer stringTokenizer = new StringTokenizer(line, ",");

                while (stringTokenizer.hasMoreElements()) {
                    int ID = Integer.parseInt(stringTokenizer.nextElement().toString());
                    String Org = stringTokenizer.nextElement().toString();
                    String Dest = stringTokenizer.nextElement().toString();
                    int D = Integer.parseInt(stringTokenizer.nextElement().toString());
                    int MT = Integer.parseInt(stringTokenizer.nextElement().toString());
                    int YA = Integer.parseInt(stringTokenizer.nextElement().toString());
                    int HA = Integer.parseInt(stringTokenizer.nextElement().toString());
                    int MIN = Integer.parseInt(stringTokenizer.nextElement().toString());
                    int S = Integer.parseInt(stringTokenizer.nextElement().toString());
                    Double FF = Double.parseDouble(stringTokenizer.nextElement().toString());
                    flight rv = new flight(ID, Org, Dest, D, MT, YA, HA, MIN, S, FF);
                    FT.add(rv);

                }

            }
            BR.close();

        } catch (IOException | NumberFormatException e) {
            String errmsg = e.getMessage();
            System.out.println("File not found:" + errmsg);
        } // end of Catch
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        page = new javax.swing.JTextArea();
        All_flight = new javax.swing.JButton();
        btn_passengers = new javax.swing.JButton();
        btn_report = new javax.swing.JButton();
        Display_panel = new javax.swing.JPanel();
        Combo1 = new javax.swing.JComboBox<>();
        Display = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        Display_panel1 = new javax.swing.JPanel();
        Combo2 = new javax.swing.JComboBox<>();
        Display1 = new javax.swing.JButton();
        cancel1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        page.setColumns(20);
        page.setRows(5);
        jScrollPane1.setViewportView(page);

        All_flight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        All_flight.setText("Display All flight");
        All_flight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                All_flightActionPerformed(evt);
            }
        });

        btn_passengers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_passengers.setText("Display Passengers");
        btn_passengers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_passengersActionPerformed(evt);
            }
        });

        btn_report.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_report.setText("Report");
        btn_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportActionPerformed(evt);
            }
        });

        Display.setText("Display");
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Display_panelLayout = new javax.swing.GroupLayout(Display_panel);
        Display_panel.setLayout(Display_panelLayout);
        Display_panelLayout.setHorizontalGroup(
            Display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Display_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Combo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Display_panelLayout.setVerticalGroup(
            Display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Display_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Display)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancel)
                .addContainerGap())
        );

        Display1.setText("Display Report");
        Display1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Display1ActionPerformed(evt);
            }
        });

        cancel1.setText("Cancel");
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Display_panel1Layout = new javax.swing.GroupLayout(Display_panel1);
        Display_panel1.setLayout(Display_panel1Layout);
        Display_panel1Layout.setHorizontalGroup(
            Display_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Display_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Display_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancel1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(Display1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(Combo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        Display_panel1Layout.setVerticalGroup(
            Display_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Display_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Display1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancel1)
                .addContainerGap())
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(All_flight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_passengers, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(btn_report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Display_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Display_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(All_flight)
                        .addGap(18, 18, 18)
                        .addComponent(btn_passengers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Display_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_report)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Display_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_passengersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_passengersActionPerformed
        // TODO add your handling code here:
        Display_panel.setVisible(true);
        All_flight.setEnabled(false);
        btn_report.setEnabled(false);
        btn_passengers.setEnabled(false);
    }//GEN-LAST:event_btn_passengersActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        Display_panel.setVisible(false);
        All_flight.setEnabled(true);
        btn_report.setEnabled(true);
        btn_passengers.setEnabled(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        // TODO add your handling code here:
        Display_panel1.setVisible(false);
        All_flight.setEnabled(true);
        btn_report.setEnabled(true);
        btn_passengers.setEnabled(true);
    }//GEN-LAST:event_cancel1ActionPerformed

    private void Display1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Display1ActionPerformed
        // TODO add your handling code here:
        int Flight_code = Integer.parseInt(Combo2.getSelectedItem().toString());
        
        double flight_fare =0;
        for (int i =0; i<FT.size(); i++){
            if (FT.get(i).getIDs() == Flight_code){
                flight_fare = FT.get(i).getFlight_fare();
            }
        }
        page.setText("");

        page.append("\n\t\t    ----Report for  Flight Number:" + Combo2.getSelectedItem().toString() + "----\n\n");
        page.append("\n\t    ----The list of passengers from the Selected Flight Number  ----\n\n");
        int count = 0;
        int number=0;
        for (int i = 0; i < PGA.size(); i++) {
            StringBuilder sb = new StringBuilder();
            if (Flight_code == PGA.get(i).getFlightNumber()) {
                ++count;
                
                sb.append("\n\t---------------------------------------\n");
                sb.append("\n\t Passenger No : " + (number + 1) + "\n");
                sb.append("\n\t Passport Number          : " + PGA.get(i).getPassport_no());
                sb.append("\n\t Name                     : " + PGA.get(i).getFirstName() + " " + PGA.get(i).getLastName());
                sb.append("\n\t Flight Fare_______________________________________: " + flight_fare);
               
                page.append(sb.toString());
            }
        }

        if (count == 0) {
            page.append("\n\t\t    ----No Passenger found for the selected flight number ----\n\n");
        } else {
            page.append("\n\t Total Fare paid by passengers________________________: " + (flight_fare *count));
            
        }
        
        
    }//GEN-LAST:event_Display1ActionPerformed

    private void btn_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportActionPerformed
        // TODO add your handling code here:
        Display_panel1.setVisible(true);
        All_flight.setEnabled(false);
        btn_report.setEnabled(false);
        btn_passengers.setEnabled(false);
    }//GEN-LAST:event_btn_reportActionPerformed

    private void All_flightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_All_flightActionPerformed
        // TODO add your handling code here:
        page.setText("");
        
        
        page.append("\n\t\t    ----Flight Details ----\n\n");
        
        for (int i=0; i<FT.size(); i++){
            StringBuilder sb = new StringBuilder();
            
            String D;
            String M;
            
            if (FT.get(i).getDays()<=9){
                 D = "0" + FT.get(i).getDays();
            } else {
                D = Integer.toString(FT.get(i).getDays());
               
            }
             if (FT.get(i).getMonth() <= 9 ){
                 M = "0" + FT.get(i).getMonth();
             } else {
                 M = Integer.toString(FT.get(i).getMonth());
             }
            String HH;
            String MM;

            if (FT.get(i).getHours() <= 9) {
                HH = "0" + FT.get(i).getHours();
            } else {
                HH = Integer.toString(FT.get(i).getHours());

            }
            if (FT.get(i).getMinutes() <= 9) {
                MM= "0" + FT.get(i).getMonth();
            }
            else {
                MM = Integer.toString(FT.get(i).getMinutes());
            }
            sb.append("\n\t---------------------------------------\n");
            sb.append("\n\t -------Flight Searl No : " + (i + 1) +"------------" );
            sb.append("\n\t Flight Number/ID          : " + FT.get(i).getIDs());
            sb.append("\n\t Origin Airport Code       : " + FT.get(i).getOrigin());
            sb.append("\n\t Detination Airprot COde   : " + FT.get(i).getDestination());
            sb.append("\n\t Date                      : " + D +"/"+ M + "/" +FT.get(i).getYear());
            sb.append("\n\t Time                      : " + HH+":"+MM);
            sb.append("\n\t Seat Capacity             : " + FT.get(i).getSeats() );
            sb.append("\n\t Flight Fare               : " + FT.get(i).getFlight_fare() );
            
            sb.append("\n\t---------------------------------------\n");
            page.append(sb.toString());
            
        }
    }//GEN-LAST:event_All_flightActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        // TODO add your handling code here:
        int Flight_code = Integer.parseInt(Combo1.getSelectedItem().toString());
        page.setText("");

        page.append("\n\t\t    ----The Selected Flight Number:" + Combo1.getSelectedItem().toString() +"----\n\n");
        
        int count =0;
        int number =0;
        for(int i=0; i<PGA.size(); i++){
             StringBuilder sb = new StringBuilder();
            if ( Flight_code == PGA.get(i).getFlightNumber()){
                ++count;
                page.append("\n\t    ----The list of passengers from the Selected Flight Number  ----\n\n");
                sb.append("\n\t---------------------------------------\n");
                sb.append("\n\t -------Passenger No : " + (number + 1) + "------------");
                sb.append("\n\t Passport Number          : " + PGA.get(i).getPassport_no());
                sb.append("\n\t Name                     : " + PGA.get(i).getFirstName() + " "+ PGA.get(i).getLastName());
                sb.append("\n\t Email Address            : " + PGA.get(i).getEmail());
                sb.append("\n\t Flight Number            : " + PGA.get(i).getFlightNumber());
                sb.append("\n\t Seat                     : " +PGA.get(i).getRow() + " "+ PGA.get(i).getSeat());
                page.append(sb.toString());
            }
        }
        
        if (count ==0){
            page.append("\n\t\t    ----No Passenger found for the selected flight ----\n\n");
        }
    }//GEN-LAST:event_DisplayActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Welcome greet= new Welcome();
        greet.setVisible(true);
        this.close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton All_flight;
    private javax.swing.JComboBox<String> Combo1;
    private javax.swing.JComboBox<String> Combo2;
    private javax.swing.JButton Display;
    private javax.swing.JButton Display1;
    private javax.swing.JPanel Display_panel;
    private javax.swing.JPanel Display_panel1;
    private javax.swing.JButton btn_passengers;
    private javax.swing.JButton btn_report;
    private javax.swing.JButton cancel;
    private javax.swing.JButton cancel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea page;
    // End of variables declaration//GEN-END:variables
}
